AliHaydarAtma.MVC/Controllers/Api/MusteriController.cs
using AliHaydarAtma.Entites.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace AliHaydarAtma.MVC.Controllers.Api
{
    public class MusteriController : ApiController
    {
        private SatisContext db;
        public MusteriController()
        {
            db = new SatisContext();
        }

        [HttpGet]

        public IHttpActionResult GetMusteris()
        {
            var musteris = db.Musteri.Where(x => x.MusteriDurumu == true).ToList();
            return Ok(musteris);
        }

        [HttpGet]
        public IHttpActionResult GetMusteri(int id)
        {
            var musteri = db.Musteri.SingleOrDefault(x => x.MusteriId == id);
            if (musteri == null)
                return NotFound();
            return Ok(musteri);

        }
        [HttpPost]
        public IHttpActionResult AddMusteri(Musteri pMusteri)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            db.Musteri.Add(pMusteri);
            db.SaveChanges();
            return Ok(pMusteri);
        }

        [HttpPut]
        public IHttpActionResult UpdateMusteri(int id, Musteri pMusteri)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var musteri = db.Musteri.SingleOrDefault(x => x.MusteriId == id);
            if (musteri == null)
                return NotFound();

            musteri.MusteriAdi = pMusteri.MusteriAdi;
            musteri.MusteriSoyadi = pMusteri.MusteriSoyadi;
            musteri.DogumTarihi = pMusteri.DogumTarihi;
            musteri.MusteriDurumu = pMusteri.MusteriDurumu;
            db.SaveChanges();

            return Ok(musteri);
        }

        [HttpDelete]
        public IHttpActionResult DeleteMusteri(int id)
        {
            var musteri = db.Musteri.SingleOrDefault(x => x.MusteriId == id);
            if (musteri == null)
                return NotFound();
            db.Musteri.Remove(musteri);
            db.SaveChanges();

            return Ok();
        }
    }
}

AliHaydarAtma.MVC/Controllers/MusteriController.cs
using AliHaydarAtma.Entites.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace AliHaydarAtma.MVC.Controllers
{
    public class MusteriController : Controller
    {
        // GET: Musteri
        SatisContext db = new SatisContext();
        public ActionResult Index(string musteriAdi, int page=1)
        {
            var musteriler = db.Musteri.AsNoTracking().Where(x => x.MusteriDurumu == true || x.MusteriDurumu == false);
            if (!string.IsNullOrEmpty(musteriAdi))
            {
                musteriler = musteriler.Where(x => x.MusteriAdi.Contains(musteriAdi) || x.MusteriSoyadi.Contains(musteriAdi));
            }


            return View(musteriler.ToList());
        }

        [HttpGet]
        public ActionResult Ekle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Ekle(Musteri pMusteri)
        {
            pMusteri.MusteriDurumu = true;
            db.Musteri.Add(pMusteri);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Sil(int id)
        {
            Musteri musteri = db.Musteri.Find(id);
            db.Musteri.Remove(musteri);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Guncelle(int id)
        {
            Musteri musteri = db.Musteri.Find(id);
            return View(musteri);
        }
        [HttpPost]
        public ActionResult Guncelle(Musteri pMusteri)
        {
            Musteri musteri = db.Musteri.Find(pMusteri.MusteriId);
            musteri.MusteriAdi = pMusteri.MusteriAdi;
            musteri.MusteriSoyadi = pMusteri.MusteriSoyadi;
            musteri.Cinsiyet = pMusteri.Cinsiyet;
            musteri.DogumTarihi = pMusteri.DogumTarihi;
            musteri.MusteriDurumu = true;
            db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

AliHaydarAtma.MVC/Views/Musteri/Ekle.cshtml
@model AliHaydarAtma.Entites.Model.Musteri
@{
    ViewBag.Title = "Ekle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div style="text-align: center; background-color: #1CB15F ;color:white;font-family:'Century Gothic';margin:5px">
    <h2><b>Musteri Ekleme</b></h2>
</div>

<div class="form-group" style="margin:5px">
    @using (Html.BeginForm("Ekle", "Musteri", FormMethod.Post))
    {
        @Html.Label("Musteri Adı")
        @Html.TextBoxFor(m => m.MusteriAdi, new { @class = "form-control" })
        <br />
        @Html.Label("Musteri Soyadı")
        @Html.TextBoxFor(m => m.MusteriSoyadi, new { @class = "form-control" })
                <br />
        @Html.Label("Dogum Tarihi")
        @Html.TextBoxFor(m => m.DogumTarihi, new { @class = "form-control" })
        
        <br />
        @Html.Label("Cinsiyet")
        @Html.TextBoxFor(m => m.Cinsiyet, new { @class = "form-control" })
        <br />
        <button style="background-color: #1CB15F;color:white"> Ekle </button>
    }
</div>

AliHaydarAtma.MVC/Views/Musteri/Guncelle.cshtml
@model AliHaydarAtma.Entites.Model.Musteri
@{
    ViewBag.Title = "Guncelle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div style="text-align: center; background-color: #1CB15F ;color:white;font-family:'Century Gothic';margin:5px">
    <h2><b>@Model.MusteriAdi&nbsp;@Model.MusteriSoyadi Güncelleme Sayfası </b></h2>
</div>


<div class="form-group" style="margin:5px">
    @using (Html.BeginForm("Guncelle", "Musteri", FormMethod.Post))
    {
        @Html.Label("Musteri Id")
        @Html.TextBoxFor(m => m.MusteriId, new { @class = "form-control", @readonly = "readonly" })
        <br />
        @Html.Label("Musteri Adı")
        @Html.TextBoxFor(m => m.MusteriAdi, new { @class = "form-control" })
        <br />
        @Html.Label("Musteri Soyadı")
        @Html.TextBoxFor(m => m.MusteriSoyadi, new { @class = "form-control" })

        <br />
        @Html.Label("Cinsiyet")
        @Html.TextBoxFor(m => m.Cinsiyet, new { @class = "form-control" })
        <br />
        <br />
        @Html.Label("Dogum Tarihi")
        @Html.TextBoxFor(m => m.DogumTarihi, new { @class = "form-control" })
        <br />
        <button class="btn btn-primary" style="background-color: #1CB15F;color:white"> Güncelle </button>
    }
</div>

AliHaydarAtma.MVC/Views/Musteri/Index.cshtml
@using AliHaydarAtma.Entites.Model
@model List<Musteri>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div style="text-align: center; color: white; background-color: #1C2E3E;margin-bottom:5px">
    <h2><b> Musteri Listesi </b></h2>
</div>
<div style="margin:15px" class="form-group">
    <table class="table table-bordered">
        <thead>
            <tr style="text-align: center; background-color: #1C2E0E;color:white">
                <th>Musteri Id</th>
                <th>Musteri Adi</th>
                <th>Musteri Soyadi</th>
                <th>Dogum Tarihi</th>
                <th>Musteri Cinsiyet</th>
                <th>Durumu</th>
                <th>Islem</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var mstr in Model)
            {
                <tr>
                    <td>@mstr.MusteriId</td>
                    <td>@mstr.MusteriAdi</td>
                    <td>@mstr.MusteriSoyadi</td>
                    <td>@mstr.DogumTarihi</td>
                    <td>@mstr.Cinsiyet</td>
                    <td>@mstr.MusteriDurumu</td>
                    <td>
                        <a class="btn btn-success" href="/Musteri/Guncelle/@mstr.MusteriId"> Guncelle </a>
                        <a class="btn btn-danger" href="/Musteri/Sil/@mstr.MusteriId"> Sil </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <button class="btn btn-primary" type="button" data-toggle="modal" data-target="#musteriEkleModal"> Yeni Musteri Ekle</button>

    <div class="modal fade" id="musteriEkleModal" tabindex="-1" role="dialog" aria-labelledby="">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"></span></button>
                    <h4 class="modal-title" id="myModalLabel">Musteri Ekle</h4>
                </div>
                <form method="post" action="/Musteri/Ekle">
                    <div class="modal-body">
                        <div class="form-group">
                            <label>
                                Musteri Adi
                            </label>

                            <input type="text" name="MusteriAdi" class="form-control" />
                        </div>
                        <div class="form-group">
                            <label>
                                Musteri Soyadi
                            </label>
                            <input type="text" name="MusteriSoyadi" class="form-control" />
                        </div>
                        <div class="form-group">
                            <label>
                                Dogum Tarihi
                            </label>
                            <input type="text" name="DogumTarihi" class="form-control" />
                        </div>
                        <div class="form-group">
                            <label>
                                Musteri Cinsiyeti
                            </label>
                            <input type="text" name="Cinsiyet" class="form-control" />
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">İptal Et</button>
                        <button type="submit" class="btn btn-primary">Ekle</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>