AliHaydarAtma.MVC/Controllers/Api/KategoriController.cs
using AliHaydarAtma.Entites.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace AliHaydarAtma.MVC.Controllers.Api
{
    public class KategoriController : ApiController
    {
        private SatisContext db;
        public KategoriController()
        {
            db = new SatisContext();
        }

        [HttpGet]

        public IHttpActionResult GetKategoris()
        {
            var kategoris = db.Kategori.Where(x => x.KategoriDurumu == true).ToList();
            return Ok(kategoris);
        }

        [HttpGet]
        public IHttpActionResult GetKategori(int id)
        {
            var kategori = db.Kategori.SingleOrDefault(x => x.KategoriId == id);
            if(kategori == null)           
                return NotFound();
            return Ok(kategori);
            
        }
        [HttpPost]
        public IHttpActionResult AddKategori(Kategori pKategori)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            db.Kategori.Add(pKategori);
            db.SaveChanges();
            return Ok(pKategori);
        }

        [HttpPut]
        public IHttpActionResult UpdateKategori(int id, Kategori pKategori)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var kategori = db.Kategori.SingleOrDefault(x => x.KategoriId == id);
            if (kategori == null)
                return NotFound();

            kategori.KategoriAdi = pKategori.KategoriAdi;
            kategori.KategoriDurumu = pKategori.KategoriDurumu;
            kategori.KategoriAciklama = pKategori.KategoriAciklama;
            db.SaveChanges();

            return Ok(kategori);
        }

        [HttpDelete]
        public IHttpActionResult DeleteKategori(int id)
        {
            var kategori = db.Kategori.SingleOrDefault(x => x.KategoriId == id);
            if (kategori == null)
                return NotFound();
            db.Kategori.Remove(kategori);
            db.SaveChanges();

            return Ok();
        }
    }
}

AliHaydarAtma.MVC/Controllers/KategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AliHaydarAtma.Entites.Model;

namespace AliHaydarAtma.MVC.Controllers
{
    public class KategoriController : Controller
    {
        SatisContext db = new SatisContext();
        // GET: Kategori
        public ActionResult Index()
        {
            List<Kategori> kategoriler = db.Kategori.Where(x => x.KategoriDurumu == true).ToList();
            return View(kategoriler);
        }

        public ActionResult Sil(int id)
        {
            Kategori ktgr = db.Kategori.Find(id);
            ktgr.KategoriDurumu = false;
            db.SaveChanges();
            return RedirectToAction("index");
        }
        [HttpGet]
        public ActionResult Ekle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Ekle(Kategori pktgr)
        {
            Kategori ktgr = new Kategori();
            ktgr.KategoriAciklama = pktgr.KategoriAciklama;
            ktgr.KategoriAdi = pktgr.KategoriAdi;
            ktgr.KategoriDurumu = true;

            db.Kategori.Add(ktgr);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Guncelle(int id)
        {
            Kategori ktgr = db.Kategori.Find(id);
            return View(ktgr);
        }
        [HttpPost]
        public ActionResult Guncelle(Kategori pktgr)
        {
            Kategori ktgr = db.Kategori.Find(pktgr.KategoriId);
            ktgr.KategoriAdi = pktgr.KategoriAdi;
            ktgr.KategoriAciklama = pktgr.KategoriAciklama;
            ktgr.KategoriDurumu = true;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

AliHaydarAtma.MVC/Views/Kategori/Ekle.cshtml
@model AliHaydarAtma.Entites.Model.Kategori
@{
    ViewBag.Title = "Ekle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div style="text-align:center;color:coral">
    <h2><b> Kategori Ekle</b></h2>
</div>
<div style="margin:15px" class="form-group">
    @using (Html.BeginForm("Ekle", "Kategori", FormMethod.Post))
    {
        @Html.LabelFor(x => x.KategoriAdi)
        @Html.TextBoxFor(x => x.KategoriAdi, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.KategoriAciklama)
        @Html.TextBoxFor(x => x.KategoriAciklama, new { @class = "form-control" })
        <br />
        <button class="btn btn-success"> Kategori Ekle</button>
    }
</div>

AliHaydarAtma.MVC/Views/Kategori/Guncelle.cshtml
@using AliHaydarAtma.Entites.Model
@model Kategori
@{
    ViewBag.Title = "Guncelle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div style="margin:15px;text-align:center;color:blueviolet">
    <h2><b>Guncelle</b></h2>
</div>
<div>
    @using (Html.BeginForm("Guncelle", "Kategori", FormMethod.Post))
    {
        @Html.LabelFor(x => x.KategoriId)
        @Html.TextBoxFor(x => x.KategoriId, new { @class = "form-control", @readonly = "readonly" })
        <br />
        @Html.LabelFor(x => x.KategoriAdi)
        @Html.TextBoxFor(x => x.KategoriAdi, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.KategoriAciklama)
        @Html.TextBoxFor(x => x.KategoriAciklama, new { @class = "form-control" })
        <br />
        <button class="btn btn-success"> Guncelle </button>
    }
</div>

AliHaydarAtma.MVC/Views/Kategori/Index.cshtml
@using AliHaydarAtma.Entites.Model
@model List<Kategori>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div style="text-align: center; color: white; background-color: #1C2E3E;margin-bottom:5px">
    <h2><b> Kategori Listesi </b></h2>
</div>
<div style="margin:15px" class="form-group">
    <table class="table table-bordered">
        <thead>
            <tr style="text-align: center; background-color: #1C2E0E;color:white">
                <th>Kategori Id</th>
                <th>Kategori Adi</th>
                <th>Aciklama</th>
                <th>Durumu</th>
                <th>Islem</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var ktgr in Model)
            {
                <tr>
                    <td>@ktgr.KategoriId</td>
                    <td>@ktgr.KategoriAdi</td>
                    <td>@ktgr.KategoriAciklama</td>
                    <td>@ktgr.KategoriDurumu</td>
                    <td>
                        <a class="btn btn-success" href="/Kategori/Guncelle/@ktgr.KategoriId"> Guncelle </a>
                        <a class="btn btn-danger" href="/Kategori/Sil/@ktgr.KategoriId"> Sil </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <button class="btn btn-primary" type="button" data-toggle="modal" data-target="#kategoriEkleModal"> Yeni Kategori Ekle</button>

    <div class="modal fade" id="kategoriEkleModal" tabindex="-1" role="dialog" aria-labelledby="">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"></span></button>
                    <h4 class="modal-title" id="myModalLabel">Kategori Ekle</h4>
                </div>
                <form method="post" action="/Kategori/Ekle">
                    <div class="modal-body">
                        <div class="form-group">
                            <label>
                                Kategori Adı
                            </label>

                            <input type="text" name="KategoriAdi" class="form-control" />
                        </div>
                        <div class="form-group">
                            <label>
                                Kategori Açıklama
                            </label>
                            <input type="text" name="KategoriAciklama" class="form-control" />
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">İptal Et</button>
                        <button type="submit" class="btn btn-primary">Ekle</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>