AliHaydarAtma.MVC/Controllers/Api/UrunController.cs
using AliHaydarAtma.Entites.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace AliHaydarAtma.MVC.Controllers.Api
{
    public class UrunController : ApiController
    {
        private SatisContext db;
        public UrunController()
        {
            db = new SatisContext();
        }

        [HttpGet]

        public IHttpActionResult GetUruns()
        {
            var uruns = db.Urun.Where(x => x.UrunDurumu == true).ToList();
            return Ok(uruns);
        }

        [HttpGet]
        public IHttpActionResult GetUrun(int id)
        {
            var urun = db.Urun.SingleOrDefault(x => x.UrunId == id);
            if (urun == null)
                return NotFound();
            return Ok(urun);

        }
        [HttpPost]
        public IHttpActionResult AddUrun(Urun pUrun)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            db.Urun.Add(pUrun);
            db.SaveChanges();
            return Ok(pUrun);
        }

        [HttpPut]
        public IHttpActionResult UpdateUrun(int id, Urun pUrun)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var urun = db.Urun.SingleOrDefault(x => x.UrunId == id);
            if (urun == null)
                return NotFound();

            urun.UrunAdi = pUrun.UrunAdi;
            urun.UrunKodu = pUrun.UrunKodu;
            urun.UrunFiyat = pUrun.UrunFiyat;
            urun.UrunStok = pUrun.UrunStok;
            urun.UrunDurumu = pUrun.UrunDurumu;
            db.SaveChanges();

            return Ok(urun);
        }

        [HttpDelete]
        public IHttpActionResult DeleteUrun(int id)
        {
            var urun = db.Urun.SingleOrDefault(x => x.UrunId == id);
            if (urun == null)
                return NotFound();
            db.Urun.Remove(urun);
            db.SaveChanges();

            return Ok();
        }
    }
}

AliHaydarAtma.MVC/Controllers/UrunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AliHaydarAtma.Entites.Model;

namespace AliHaydarAtma.MVC.Controllers
{
    public class UrunController : Controller
    {
        SatisContext db = new SatisContext();
        // GET: Urun
        public ActionResult Index(string aranacakKelime)
        {
            var urunler = db.Urun.Include("Kategori").Where(x => x.UrunDurumu == true);
            if (!string.IsNullOrEmpty(aranacakKelime))
            {
                urunler = urunler.Where(x => x.UrunAdi.Contains(aranacakKelime));
            }
            

            return View(urunler.ToList());
        }


        public ActionResult Sil(int id)
        {
            Urun ktp = db.Urun.Find(id);
            ktp.UrunDurumu = false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Guncelle(int id)
        {
            Urun urn = db.Urun.Find(id);

            List<SelectListItem> kategoriler = db.Kategori.AsNoTracking().Where(x => x.KategoriDurumu == true)
                .Select(s => new SelectListItem
                {
                    Value = s.KategoriId.ToString(),
                    Text = s.KategoriAdi
                }).ToList();
            ViewBag.Kategoriler = kategoriler;
            return View(urn);
        }

        [HttpPost]
        public ActionResult Guncelle(Urun pUrun)
        {
            Urun urn = db.Urun.Find(pUrun.UrunId);
            urn.UrunAdi = pUrun.UrunAdi;
            urn.UrunKodu = pUrun.UrunKodu;
            urn.UrunFiyat = pUrun.UrunFiyat;
            urn.UrunStok = pUrun.UrunStok;
            urn.Kategori = db.Kategori.Find(pUrun.Kategori.KategoriId);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet] // Sayfa yüklendiğinde çalışacak

        public ActionResult Ekle()
        {

            List<SelectListItem> kategoriler = db.Kategori.AsNoTracking().Where(x => x.KategoriDurumu == true)
                .Select(s => new SelectListItem
                {
                    Value = s.KategoriId.ToString(),
                    Text = s.KategoriAdi
                }).ToList();

            ViewBag.Kategoriler = kategoriler;
            return View();
        }

        [HttpPost] // Sayfa içerisinde bir yerde sayfayı post edildiğinde çalışacak
        public ActionResult Ekle(Urun pUrun)
        {
            pUrun.Kategori = db.Kategori.Find(pUrun.KategoriId);
            pUrun.UrunDurumu = true;
            db.Urun.Add(pUrun);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

AliHaydarAtma.MVC/Views/Urun/Ekle.cshtml
@model AliHaydarAtma.Entites.Model.Urun

@{
    ViewBag.Title = "Ekle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div style="font-family:'Century Gothic'">

    <div style="text-align: center; background-color: #1C2E3E;color:white;margin:15px">
            <h2><b>Urun Ekle</b></h2>
    </div>
</div>

<div style="margin:15px">
    @using (Html.BeginForm("Ekle", "Urun", FormMethod.Post))
    {
        @Html.Label("Kategorisi")
        @Html.DropDownListFor(x => x.KategoriId, (List<SelectListItem>)ViewBag.Kategoriler, new { @class = "form-control" })
        <br />

        @Html.Label("Urun Adı")
        @Html.TextBoxFor(x => x.UrunAdi, new { @class = "form-control" })
        <br />

        @Html.Label("Urun Kodu")
        @Html.TextBoxFor(x => x.UrunKodu, new { @class = "form-control" })
        <br />
        @Html.Label("Urun Fiyati")
        @Html.TextBoxFor(x => x.UrunFiyat, new { @class = "form-control" })
        <br />
        @Html.Label("Urun Stok")
        @Html.TextBoxFor(x => x.UrunStok, new { @class = "form-control" })
        <br />
        <button style="text-align: center; background-color: #1C2E3E; color: white"> <b>Urun ekle</b></button>
    }
</div>

AliHaydarAtma.MVC/Views/Urun/Guncelle.cshtml
@model AliHaydarAtma.Entites.Model.Urun
@{
    ViewBag.Title = "Guncelle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div style="font-family:'Century Gothic'">

    <div style="text-align: center; background-color: #1C2E3E;color:white;margin:15px">
        <h2><b> Id : @Model.UrunId - Urun Guncelle</b></h2>
    </div>
</div>

<div style="margin:15px">
    @using (Html.BeginForm("Guncelle", "Urun", FormMethod.Post))
    {
        @Html.Label("Urun Id ")
        @Html.TextBoxFor(x => x.UrunId, new { @class = "form-control" ,@readonly ="readonly" })
        <br />
        @Html.Label("Kategorisi")
        @Html.DropDownListFor(x => x.Kategori.KategoriId, (List<SelectListItem>)ViewBag.Kategoriler, new { @class = "form-control" })
        <br />

        @Html.Label("Urun Adı")
        @Html.TextBoxFor(x => x.UrunAdi, new { @class = "form-control" })
        <br />

        @Html.Label("Urun Kodu")
        @Html.TextBoxFor(x => x.UrunKodu, new { @class = "form-control" })
        <br />
        @Html.Label("Urun Fiyati")
        @Html.TextBoxFor(x => x.UrunFiyat, new { @class = "form-control" })
        <br />
        @Html.Label("Urun Stok")
        @Html.TextBoxFor(x => x.UrunStok, new { @class = "form-control" })
        <br />
        <button style="text-align: center; background-color: #1C2E3E; color: white;height:40px"> <b>Güncelle</b></button>
    }
</div>

AliHaydarAtma.MVC/Views/Urun/Index.cshtml
@using AliHaydarAtma.Entites.Model
@model List<Urun>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div style="font-family:'Century Gothic'">

    <div style="text-align: center; color: white; background-color: #1C2E3E;margin-bottom:5px">
        <h2><b> Urun Listesi </b></h2>
    </div>
    <div class="form-group" style="text-align:right;margin:15px">
        @using (Html.BeginForm("Index", "Urun", FormMethod.Get))
        {
            <div><b> Urun Adı : </b> @Html.TextBox("aranacakKelime")&nbsp;<button style="color: white; background-color: #1C2E3E"> Arama yap</button> </div>}
    </div>
    <div style="margin:15px">
        <table class="table table-bordered">
            <thead>
                <tr style="text-align: center; background-color: #1C2E0E;color:white">
                    <th style="width:7%">UrunId</th>
                    <th>UrunAdi</th>
                    <th>Kategorisi</th>
                    <th>UrunStok</th>
                    <th>UrunFiyat</th>
                    <th style="width:8%">UrunKodu</th>
                    <th>İşlem</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var urn in Model)
                {
                    <tr>
                        <td>@urn.UrunId</td>
                        <td>@urn.UrunAdi</td>
                        <td>@urn.Kategori.KategoriAdi</td>
                        <td>@urn.UrunStok</td>
                        <td>@urn.UrunFiyat</td>
                        <td>@urn.UrunKodu</td>
                        <td>
                            <a class="btn btn-danger" href="/Urun/Sil/@urn.UrunId"> Sil </a>&nbsp;
                            <a class="btn btn-primary" href="/Urun/Guncelle/@urn.UrunId"> Güncelle </a>&nbsp;
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<button class="btn btn-primary" type="button" data-toggle="modal" data-target="#urunEkleModal"> Yeni Urun Ekle</button>

<div class="modal fade" id="urunEkleModal" tabindex="-1" role="dialog" aria-labelledby="">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"></span></button>
                <h4 class="modal-title" id="myModalLabel">Urun Ekle</h4>
            </div>
            <form method="post" action="/Urun/Ekle">
                <div class="modal-body">
                    <div class="form-group">
                        <label>
                            Urun Adi
                        </label>

                        <input type="text" name="UrunAdi" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label>
                            Kategori
                        </label>
                        <input type="text" name="KategoriId" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label>
                            Urun Stok
                        </label>
                        <input type="text" name="UrunStok" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label>
                            Urun Fiyat
                        </label>
                        <input type="text" name="UrunFiyat" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label>
                            Urun Kodu
                        </label>
                        <input type="text" name="UrunKodu" class="form-control" />
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">İptal Et</button>
                    <button type="submit" class="btn btn-primary">Ekle</button>
                </div>
            </form>
        </div>
    </div>
</div>