AliHaydarAtma.MVC/Controllers/Api/SepetController.cs
using AliHaydarAtma.Entites.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace AliHaydarAtma.MVC.Controllers.Api
{
    public class SepetController : ApiController
    {
        private SatisContext db;
        public SepetController()
        {
            db = new SatisContext();
        }

        [HttpGet]

        public IHttpActionResult GetSepets()
        {
            var sepets = db.Sepet.Where(x => x.SepetDurumu == true).ToList();
            return Ok(sepets);
        }

        [HttpGet]
        public IHttpActionResult GetSepet(int id)
        {
            var sepet = db.Sepet.SingleOrDefault(x => x.SepetId == id);
            if (sepet == null)
                return NotFound();
            return Ok(sepet);

        }
        [HttpPost]
        public IHttpActionResult AddSepet(Sepet pSepet)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            db.Sepet.Add(pSepet);
            db.SaveChanges();
            return Ok(pSepet);
        }

        [HttpPut]
        public IHttpActionResult UpdateSepet(int id, Sepet pSepet)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var sepet = db.Sepet.SingleOrDefault(x => x.SepetId == id);
            if (sepet == null)
                return NotFound();

            sepet.SepetAdet = pSepet.SepetAdet;
            sepet.SepetToplam = pSepet.SepetToplam;
            sepet.SepetDurumu = pSepet.SepetDurumu;
            sepet.Musteri.MusteriAdi = pSepet.Musteri.MusteriAdi;
            sepet.Urun.UrunAdi = pSepet.Urun.UrunAdi;
            db.SaveChanges();

            return Ok(sepet);
        }

        [HttpDelete]
        public IHttpActionResult DeleteSepet(int id)
        {
            var sepet = db.Sepet.SingleOrDefault(x => x.SepetId == id);
            if (sepet == null)
                return NotFound();
            db.Sepet.Remove(sepet);
            db.SaveChanges();

            return Ok();
        }
    }
}

AliHaydarAtma.MVC/Controllers/SepetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AliHaydarAtma.Entites.Model;
using System.Data.Entity;

namespace AliHaydarAtma.MVC.Controllers
{
    public class SepetController : Controller
    {
        SatisContext db = new SatisContext();
        // GET: Sepet
        public ActionResult Index()
        {
            List<Sepet> sepetler = db.Sepet.Include(x=> x.Urun).ToList();
            return View(sepetler);
        }

        public ActionResult Sil(int id)
        {
            Sepet spt = db.Sepet.Find(id);
            db.Sepet.Remove(spt);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Ekle()
        {
            List<SelectListItem> musteriler = db.Musteri.AsNoTracking().Where(x=>x.MusteriDurumu == true)
                .Select(s=> new SelectListItem
                {
                    Value = s.MusteriId.ToString(),
                    Text = s.MusteriAdi + " " + s.MusteriSoyadi
                }).ToList();

            List<SelectListItem> urunler = db.Urun.AsNoTracking().Where(x => x.UrunDurumu == true)
                .Select(s => new SelectListItem
                {
                    Value = s.UrunId.ToString(),
                    Text = s.UrunAdi
                }).ToList();

            ViewBag.Musteriler = musteriler;
            ViewBag.Urunler = urunler;
            return View();
        }

        [HttpPost]
        public ActionResult Ekle(Sepet pSepet)
        {
            pSepet.Urun = db.Urun.Find(pSepet.UrunId);
            pSepet.Musteri = db.Musteri.Find(pSepet.MusteriId);
            pSepet.SepetToplam = pSepet.Urun.UrunFiyat * pSepet.SepetAdet;
            pSepet.Urun.UrunStok -= pSepet.SepetAdet;
            pSepet.SepetDurumu = true;
            db.Sepet.Add(pSepet);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Guncelle(int id)
        {
            Sepet spt = db.Sepet.Find(id);

            List<SelectListItem> urunler = db.Urun.AsNoTracking().Where(x => x.UrunDurumu == true)
                .Select(s => new SelectListItem
                {
                    Value = s.UrunId.ToString(),
                    Text = s.UrunAdi
                }).ToList();

             List<SelectListItem> musteriler = db.Musteri.AsNoTracking().Where(x => x.MusteriDurumu == true)
                .Select(s => new SelectListItem
                {
                    Value = s.MusteriId.ToString(),
                    Text = s.MusteriAdi
                }).ToList();
            ViewBag.Kategoriler = musteriler;
            ViewBag.Musteriler = musteriler;
            ViewBag.Urunler = urunler;
            return View(spt);
        }

        [HttpPost]
        public ActionResult Guncelle(Sepet pSepet)
        {
            Sepet spt = db.Sepet.Find(pSepet.SepetId);
            spt.Musteri.MusteriAdi = pSepet.Musteri.MusteriAdi;
            spt.Urun.UrunAdi = pSepet.Urun.UrunAdi;
            spt.SepetAdet = pSepet.SepetAdet;
            spt.Urun = db.Urun.Find(pSepet.Urun.UrunId);
            spt.Musteri = db.Musteri.Find(pSepet.Musteri.MusteriAdi);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

AliHaydarAtma.MVC/Views/Sepet/Ekle.cshtml
@model AliHaydarAtma.Entites.Model.Sepet
@{
    ViewBag.Title = "Ekle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div style="text-align: center; background-color: #1CB15F ;color:white;font-family:'Century Gothic';margin:5px">
    <h2><b>Sepet Ekleme</b></h2>
</div>

<div class="form-group" style="margin:5px">
    @using (Html.BeginForm("Ekle", "Sepet", FormMethod.Post))
    {
        @Html.Label("Musteri Adi")
        @Html.DropDownListFor(x => x.MusteriId, (List<SelectListItem>)ViewBag.Musteriler, new { @class = "form-control" })
        <br />
        <br />
        @Html.Label("Urun Adi")
        @Html.DropDownListFor(x => x.UrunId, (List<SelectListItem>)ViewBag.Urunler, new { @class = "form-control" })
        <br />
        <br />
        @Html.Label("Urun Stok")
        @Html.TextBoxFor(x => x.SepetAdet, new { @class = "form-control" })      
        <br />
        <button style="background-color: #1CB15F;color:white"> Ekle </button>
    }
</div>

AliHaydarAtma.MVC/Views/Sepet/Guncelle.cshtml
@model AliHaydarAtma.Entites.Model.Sepet
@{
    ViewBag.Title = "Guncelle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div style="text-align: center; background-color: #1CB15F ;color:white;font-family:'Century Gothic';margin:5px">
    <h2><b> Güncelleme Sayfası </b></h2>
</div>


<div class="form-group" style="margin:5px">
    @using (Html.BeginForm("Guncelle", "Sepet", FormMethod.Post))
    {
        @Html.Label("Sepet Id")
        @Html.TextBoxFor(x => x.SepetId, new { @class = "form-control", @readonly = "readonly" })
        <br />
        @Html.Label("Musteri Adi")
        @Html.DropDownListFor(x => x.MusteriId, (List<SelectListItem>)ViewBag.Musteriler, new { @class = "form-control" })
        <br />
        @Html.Label("Urun Adi")
        @Html.DropDownListFor(x => x.UrunId, (List<SelectListItem>)ViewBag.Urunler, new { @class = "form-control" })
        <br />
        @Html.Label("Urun Adet")
        @Html.TextBoxFor(x => x.SepetAdet, new { @class = "form-control" })
        <br />
        <br />
        <button class="btn btn-primary" style="background-color: #1CB15F;color:white"> Güncelle </button>
    }
</div>

AliHaydarAtma.MVC/Views/Sepet/Index.cshtml
@using AliHaydarAtma.Entites.Model
@model List<Sepet>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div style="text-align: center; color: white; background-color: #1C2E3E;margin-bottom:5px">
    <h2><b> Sepet Listesi </b></h2>
</div>
<div style="margin:15px" class="form-group">
    <table class="table table-bordered">
        <thead>
            <tr style="text-align: center; background-color: #1C2E0E;color:white">
                <th>Musteri Adi</th>
                <th>Urun Adi</th>
                <th>Urun Adet</th>
                <th>Toplam Fiyat</th>
                <th>Islem</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var spt in Model)
            {
                <tr>
                    <td>@spt.MusteriId</td>
                    <td>@spt.Urun.UrunAdi</td>
                    <td>@spt.SepetAdet</td>
                    <td>@spt.SepetToplam</td>
                    <td>
                        <a class="btn btn-success" href="/Sepet/Guncelle/@spt.SepetId"> Guncelle </a>
                        <a class="btn btn-danger" href="/Sepet/Sil/@spt.SepetId"> Sil </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<a class="btn" href="/Sepet/Ekle/" style="text-align:center; background-color:#1C2E3E;color:white;margin:15px"> Sepet Ekle </a>